title: the field
author: wollemia
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The surface of interction between text and the other place
  (memories do not become words by themselves).
# social links
github_username:  wollemia # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
